### ISSUE TITLE
Can you use this for tiktok as well?

### ISSUE THREAD

**Issue by spinningsand** [go-olive/olive#12]
I noticed it worked on douyin and that you had tiktok tagged, but I wasn't sure.

**Comment by luxcgo** [comment]
Yes. Tiktok is fully supported in olive v0.2.9. Try for yourself!

**Comment by spinningsand** [comment]
Thanks for that! But I'm not exactly sure how to use it. Can you help me?

**Comment by luxcgo** [comment]
You can first download the executable file for your os platform. And change the config.toml file for your streamer.
Last simply run the command `/path/to/olive -c /path/to/config.toml`

**Comment by luxcgo** [comment]
1. `go install github.com/go-olive/olive/src/cmd/olive@latest`
2. `olive -c /path/to/config.toml`

how about trying this?

**Comment by luxcgo** [comment]
Actually, you have to download exe from https://github.com/go-olive/olive/releases. And put it somewhere, then cd that directory.

**Comment by spinningsand** [comment]
What's the difference between the to amd64? I noticed there are 2 different sizes for them.

**Comment by luxcgo** [comment]
```toml
[[Shows]]
Platform = "tiktok"
RoomID = "rpd.beans"
OutTmpl = "[{{ now | date \"2006-01-02 15-04-05\"}}][{{ .StreamerName }}]"
```

One block like this means one streamer, you can add or delete whatever streamers you want.
