### ISSUE TITLE
增加录制完毕后，运行shell的调用

### ISSUE THREAD

**Issue by UVJkiNTQ** [go-olive/olive#22]
看到roadmap里有网盘上传，其实可以利用shell来调用各种网盘工具。
可以不内置那些网盘依赖，让各种网盘工具读自己的config。例如rclone、bypy等。

**Comment by luxcgo** [comment]
我觉得行，能提供下具体的命令吗。看看程序里需要提供哪些参数，比如`{{ .FilePath }}`之类的。

**Comment by UVJkiNTQ** [comment]
一般只要file path吧，可以传 一行一个文件路径的。

https://gist.github.com/UVJkiNTQ/ae4282e8f9fe4e45b3144b57605b4178

**Comment by luxcgo** [comment]
增加`Shows.PostCmds`配置项，在任何一个`Shows`的下面都可以自定义的配置多个命令。

在录制结束的时候会自动依次执行，若中途有命令执行失败，则提前退出。

`olive`内部提供了几个已经实现好的命令（`Path`参数）

* `olivearchive`: 将文件移动到当前路径下的`archive`文件夹中。
* `olivetrash`: 将文件删除（不可恢复）。
* `olivebiliup`: 若有配置`UploadConfig`，则会根据配置自动上传至哔哩哔哩，若上传失败会执行`olivearchive`。

> 以上命令都不需要配置`Args`参数

若用户需要执行自定义命令，可将`Path`置空或配置成`oliveshell`，然后在`Args`中配置命令即可。
同时`olive`内部提供了文件路径`$FILE_PATH`作为环境变量，可直接使用。

**Comment by luxcgo** [comment]
配置文件样例

```toml
[UploadConfig]
Enable = true
ExecPath = "/xxx/biliup"

[[Shows]]
Platform = "bilibili"
RoomID = "21852"
StreamerName = "test"
OutTmpl = "[test][{{ now | date \"2006-01-02 15-04-05\"}}].flv"
[[Shows.PostCmds]]
Path = "oliveshell"
Args = ["/bin/sh", "-c", "echo $FILE_PATH"]
[[Shows.PostCmds]]
Path = "olivebiliup"
[[Shows.PostCmds]]
Path = "olivetrash"
```

模拟执行配置文件

1. 录制结束
2. 执行自定义命令`/bin/sh -c "echo $FILE_PATH"`
3. 若上条命令执行成功，执行内置命令`olivebiliup`
4. 若上条命令执行成功，执行内置命令`olivetrash`
