### ISSUE TITLE
能否单独增加个代理选项呢

### ISSUE THREAD

**Issue by jkfujr** [go-olive/olive#37]
RT，windows有点搞不太懂需要设置哪的代理

**Comment by luxcgo** [comment]
你的代理配置是什么样的呢？

**Comment by jkfujr** [comment]
用[netch](https://github.com/netchx/netch)代理olive.exe进程录youtube，但没代理上，录不了与 #35 情况一样

**Comment by luxcgo** [comment]
可以的。

其实我的意思是，你是想在 **olive** 的配置文件中加入`http(s)代理`或`socks代理`吗？
类似下面这样：

```sh
 export https_proxy=http://127.0.0.1:7890
 export http_proxy=http://127.0.0.1:7890
 export all_proxy=socks5://127.0.0.1:7890
```

**Comment by jkfujr** [comment]
好，可以让单个房间代理或者全局代理

**Comment by luxcgo** [comment]
可以设置全局代理，格式如下：
```toml
[[Envs]]
Key = "https_proxy"
Value = "http://127.0.0.1:7890"
[[Envs]]
Key = "http_proxy"
Value = "http://127.0.0.1:7890"
```
