### ISSUE TITLE
关于文件名设定

### ISSUE THREAD

**Issue by jkfujr** [go-olive/olive#38]
用反斜杠 “\” 表示一层文件夹

设定
`OutTmpl = "{{ now | date \"20060102\"}}\{{ now | date \"20060102-150405\"}}_{{ .RoomName }}【{{ .StreamerName }}】.flv"`

输出
20220720\20220720-220200_直播间标题【ID】.flv

每天都会新建一个名字是当前年月日的文件夹

**Comment by luxcgo** [comment]
这种设计不是很优雅。

现在不是已经有保存路径的选项吗，在其中加个tmpl的配置怎么样。
也能达到同样的效果。

**Comment by jkfujr** [comment]
现在的配置，请问如何配置呢
`[[Shows]]`
`Platform = "bilibili"`
`RoomID = "3"`
`StreamerName = "测试"`
`SaveDir = "E:/Video/录播/bilibili"`
`OutTmpl = "{{ now | date \"20060102-150405\"}}_{{ .RoomName }}【{{ .StreamerName }}】.flv"`

**Comment by luxcgo** [comment]
```toml
[[Shows]]
Platform = "huya"
RoomID = "wanzi"
StreamerName = "丸子呦"
SaveDir = "/Users/lucas/github/olive/{{ now | date \"2006-01-02\"}}"
```

这是个新 feature
